### ISSUE TITLE
付费电台的存在会导致程序运行崩溃

### ISSUE THREAD

**Issue by baka719** [Alovez/euro-truck-gadio-list#2]
报错如下：
```
PS E:\gadio_euro\euro-truck-gadio-list-master\euro-truck-gadio-list-master> python .\direct_gen.py
Traceback (most recent call last):
  File "E:\gadio_euro\euro-truck-gadio-list-master\euro-truck-gadio-list-master\direct_gen.py", line 17, in <module>
    print(generate_gadio_list())
  File "E:\gadio_euro\euro-truck-gadio-list-master\euro-truck-gadio-list-master\build_radio_list.py", line 42, in generate_gadio_list
    mp3, category = get_radio_info(link)
  File "E:\gadio_euro\euro-truck-gadio-list-master\euro-truck-gadio-list-master\build_radio_list.py", line 27, in get_radio_info
    mp3 = soup.select('a[href*=".mp3"]')[0].get('href')
IndexError: list index out of range
```

以上问题可以通过修改 `build_radio_list.py` 解决（直接下 zip 包用的，懒得拉 requests 了……）
```
def get_radio_info(radio_link):
    response = requests.get(BASE_URL + radio_link)
    # import pdb;pdb.set_trace()
    if not soup.select('a[href*=".mp3"]'):
        return None, None
    mp3 = soup.select('a[href*=".mp3"]')[0].get('href')
    category = soup.select('span.original_category')[0].get_text()
    return mp3, category
```
```
def generate_gadio_list():
    count = 0
    live_stream_str = ''
    for page in range(PAGES):
        response = requests.get(RADIO_LIST_URL.format(page + 1))
        soup = BeautifulSoup(response.text, "html.parser")
        # import pdb;pdb.set_trace()
        for radio in soup.select('a[href*="radios/"]'):
            title = radio.get_text().replace('|', ',')
            link = radio.get('href')
            mp3, category = get_radio_info(link)
            if mp3 or category:
                live_stream_str += RECORD_TEMPLATE.format(count=count, url=mp3, title=title, category=category)
                count += 1
    live_stream_str = f"stream_data: {count}\n" + live_stream_str
    return LIVE_STREAM_TEMPLATE % live_stream_str
```
话说机核到现在还能用这套代码抓mp3做广播，很神奇。

**Comment by Alovez** [comment]
已经改了
